precision = "bf16"
unit = "epoch"

[data]
train_shards = "./imagenet/imagenet1k-train-*.tar"
valid_shards = "./imagenet/imagenet1k-validation-*.tar"
batch_size = 512
max_seq_len = 1_000_000

[model]
size = "s"

[model.head]
task = "classification"
classes = 1000

[optimizer]
learning_rate = 0.01

[scheduler]
total = 90
warmup = 3

[logging]
frequency = 1
directory = "./runs/logs"

[checkpoint]
frequency = 10
directory = "./runs/checkpoints"

[validation]
frequency = 10
batch_size = 512
